"""Add birthday, hobbies, profile to User

Revision ID: 9074d7b15e4b
Revises: 
Create Date: 2025-05-20 19:43:22.544540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9074d7b15e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
