"""add background and family_status columns

Revision ID: f2e606eb0c9c
Revises: 9074d7b15e4b
Create Date: 2025-05-21 19:24:10.948412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e606eb0c9c'
down_revision = '9074d7b15e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('family_status', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('family_status')
        batch_op.drop_column('background')

    # ### end Alembic commands ###
